name: Setup
author: Maiko Tan
description: 'Setup workspace for building cordiverse project'
inputs:
  fetch-submodules:
    type: boolean
    description: 'Whether to fetch submodules'
    required: false
  node-version:
    type: string
    description: 'Node.js version'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      if: ${{ inputs.no-checkout == 'false' }}
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Check Yarn Version
      id: yarn-version
      shell: bash
      run: |
        VERSION=$(yarn --version)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "is-berry=$(echo $VERSION | grep -v '^1\.' | wc -l)" >> $GITHUB_OUTPUT

    - name: Get Yarn Cache Directory Path (Yarn 1)
      if: steps.yarn-version.outputs.is-berry == '0'
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Get Yarn Cache Directory Path (Yarn 2)
      if: steps.yarn-version.outputs.is-berry == '1'
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Dependencies
      id: cache-yarn
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Dependencies
      shell: bash
      run: |
        yarn
